# Generated by Django 4.0.4 on 2022-06-17 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='correct',
        ),
    ]
