# Generated by Django 4.0.4 on 2022-06-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0004_remove_answer_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
