# Generated by Django 4.0.4 on 2022-06-17 07:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0006_coop12_delete_answer_delete_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='coop12',
            name='text',
            field=models.TextField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
